development:
  adapter: postgresql
  encoding: unicode
  database: ztb_dev
  pool: 5
  username: ted
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ztb_test
  pool: 5
  username: ted
  password:
