development:
  adapter: postgresql
  encoding: unicode
  database: ztb_dev
  pool: 5
  username: ted
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ztb_production
  pool: 5
  username: ted
  password:
